### ISSUE TITLE
Location table: blank column after waterBody containing partial waterBody strings

### ISSUE THREAD

**Issue by ghost** [rascully/Stream-Monitoring-Data-Exchange-Specifications#27]
**Line in code where this issue exists:**
Unknown.

**Issue location in dataset**: https://github.com/rascully/Stream-Monitoring-Data-Exchange-Specifications/blob/master/DataIntegrationExample/data/csv/Location.csv - AIM data - waterBody column

**Issue:** There is an extra column with no header to the right of the "waterBody" column for a few AIM sites. It looks like some of their waterBody names are arranged as “Plata River, La” so the “La” portion is being placed in a new column as separated by a comma. This needs to be fixed in the code somehow.

**Action to Take:** Modify (or add) code for the AIM waterBody element to join or concatenate the strings formatted as "Plata River, La" to be contained in a single column.

---
ed edited to update broken link to dataset

**Comment by eheaston** [comment]
This has been fixed in the CombinedData.r code - **The table in GitHub will be updated with the next pull request**. 

I added a line that replaces any commas in all_data2$waterBody with | 
Now when we export data from the combined data (including the location table) to a csv this should not be an issue. 

For future reverence: this was not very common, but seemed to be occurring with AIM data, where the waterbody name included a comma. Sometimes names like 'Rio Grand' are recorded as 'Grand, Rio'.
